//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protobuf.proto
namespace PVPProtobuf
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Socket_CheckToken_Request")]
  public partial class Socket_CheckToken_Request : global::ProtoBuf.IExtensible
  {
    public Socket_CheckToken_Request() {}
    
    private string _token;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _proto_version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"proto_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int proto_version
    {
      get { return _proto_version; }
      set { _proto_version = value; }
    }
    private uint _app_user_info_number;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"app_user_info_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint app_user_info_number
    {
      get { return _app_user_info_number; }
      set { _app_user_info_number = value; }
    }
    private uint _app_user_info_custom_data_number;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"app_user_info_custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint app_user_info_custom_data_number
    {
      get { return _app_user_info_custom_data_number; }
      set { _app_user_info_custom_data_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Socket_CheckToken_Response")]
  public partial class Socket_CheckToken_Response : global::ProtoBuf.IExtensible
  {
    public Socket_CheckToken_Response() {}
    
    private PVPProtobuf.AppUserInfo _user_info = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"user_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PVPProtobuf.AppUserInfo user_info
    {
      get { return _user_info; }
      set { _user_info = value; }
    }
    private PVPProtobuf.LobbyInfo _lobby_info = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"lobby_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PVPProtobuf.LobbyInfo lobby_info
    {
      get { return _lobby_info; }
      set { _lobby_info = value; }
    }
    private PVPProtobuf.RoomInfo _room_info = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public PVPProtobuf.RoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppUserInfo")]
  public partial class AppUserInfo : global::ProtoBuf.IExtensible
  {
    public AppUserInfo() {}
    
    private uint _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private int _level;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _score;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _win_times;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int win_times
    {
      get { return _win_times; }
      set { _win_times = value; }
    }
    private int _lose_times;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"lose_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lose_times
    {
      get { return _lose_times; }
      set { _lose_times = value; }
    }
    private uint _number;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint number
    {
      get { return _number; }
      set { _number = value; }
    }
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _custom_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(10, Name=@"custom_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> custom_data
    {
      get { return _custom_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LobbyInfo")]
  public partial class LobbyInfo : global::ProtoBuf.IExtensible
  {
    public LobbyInfo() {}
    
    private int _lobby_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lobby_id
    {
      get { return _lobby_id; }
      set { _lobby_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Lobby_GetLobbyList_Request")]
  public partial class Lobby_GetLobbyList_Request : global::ProtoBuf.IExtensible
  {
    public Lobby_GetLobbyList_Request() {}
    
    private int _ext;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ext
    {
      get { return _ext; }
      set { _ext = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Lobby_GetLobbyList_Response")]
  public partial class Lobby_GetLobbyList_Response : global::ProtoBuf.IExtensible
  {
    public Lobby_GetLobbyList_Response() {}
    
    private readonly global::System.Collections.Generic.List<PVPProtobuf.LobbyInfo> _lobby_list = new global::System.Collections.Generic.List<PVPProtobuf.LobbyInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"lobby_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.LobbyInfo> lobby_list
    {
      get { return _lobby_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Lobby_EnterLobby_Request")]
  public partial class Lobby_EnterLobby_Request : global::ProtoBuf.IExtensible
  {
    public Lobby_EnterLobby_Request() {}
    
    private int _lobby_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lobby_id
    {
      get { return _lobby_id; }
      set { _lobby_id = value; }
    }
    private int _room_offset;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_offset", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_offset
    {
      get { return _room_offset; }
      set { _room_offset = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Lobby_EnterLobby_Response")]
  public partial class Lobby_EnterLobby_Response : global::ProtoBuf.IExtensible
  {
    public Lobby_EnterLobby_Response() {}
    
    private int _lobby_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lobby_id
    {
      get { return _lobby_id; }
      set { _lobby_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Pair")]
  public partial class Pair : global::ProtoBuf.IExtensible
  {
    public Pair() {}
    
    private string _key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string key
    {
      get { return _key; }
      set { _key = value; }
    }
    private byte[] _value;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"value", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] value
    {
      get { return _value; }
      set { _value = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomInfo")]
  public partial class RoomInfo : global::ProtoBuf.IExtensible
  {
    public RoomInfo() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _max_fighter_number;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"max_fighter_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_fighter_number
    {
      get { return _max_fighter_number; }
      set { _max_fighter_number = value; }
    }
    private int _max_spectator_number;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"max_spectator_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_spectator_number
    {
      get { return _max_spectator_number; }
      set { _max_spectator_number = value; }
    }
    private int _fighter_number;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fighter_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fighter_number
    {
      get { return _fighter_number; }
      set { _fighter_number = value; }
    }
    private int _spectator_number;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"spectator_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spectator_number
    {
      get { return _spectator_number; }
      set { _spectator_number = value; }
    }
    private bool _is_open;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"is_open", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_open
    {
      get { return _is_open; }
      set { _is_open = value; }
    }
    private bool _is_visible;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"is_visible", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool is_visible
    {
      get { return _is_visible; }
      set { _is_visible = value; }
    }
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _custom_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(10, Name=@"custom_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> custom_data
    {
      get { return _custom_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.RoomInfo.MemberInfo> _member_infos = new global::System.Collections.Generic.List<PVPProtobuf.RoomInfo.MemberInfo>();
    [global::ProtoBuf.ProtoMember(11, Name=@"member_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.RoomInfo.MemberInfo> member_infos
    {
      get { return _member_infos; }
    }
  
    private readonly global::System.Collections.Generic.List<uint> _random_sequence = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(12, Name=@"random_sequence", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> random_sequence
    {
      get { return _random_sequence; }
    }
  
    private int _state;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MemberInfo")]
  public partial class MemberInfo : global::ProtoBuf.IExtensible
  {
    public MemberInfo() {}
    
    private uint _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private int _category;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int category
    {
      get { return _category; }
      set { _category = value; }
    }
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _custom_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(4, Name=@"custom_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> custom_data
    {
      get { return _custom_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_CreateRoom_Request")]
  public partial class Room_CreateRoom_Request : global::ProtoBuf.IExtensible
  {
    public Room_CreateRoom_Request() {}
    
    private int _max_figter_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"max_figter_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int max_figter_number
    {
      get { return _max_figter_number; }
      set { _max_figter_number = value; }
    }
    private int _spectator_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"spectator_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spectator_number
    {
      get { return _spectator_number; }
      set { _spectator_number = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_CreateRoom_Response")]
  public partial class Room_CreateRoom_Response : global::ProtoBuf.IExtensible
  {
    public Room_CreateRoom_Response() {}
    
    private PVPProtobuf.RoomInfo _room_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PVPProtobuf.RoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_EnterRoom_Request")]
  public partial class Room_EnterRoom_Request : global::ProtoBuf.IExtensible
  {
    public Room_EnterRoom_Request() {}
    
    private int _room_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private int _category;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int category
    {
      get { return _category; }
      set { _category = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_EnteredRoom_Response")]
  public partial class Room_EnteredRoom_Response : global::ProtoBuf.IExtensible
  {
    public Room_EnteredRoom_Response() {}
    
    private PVPProtobuf.RoomInfo _room_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PVPProtobuf.RoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo> _appuser_info = new global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"appuser_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo> appuser_info
    {
      get { return _appuser_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_OtherMemberEnterRoom_Response")]
  public partial class Room_OtherMemberEnterRoom_Response : global::ProtoBuf.IExtensible
  {
    public Room_OtherMemberEnterRoom_Response() {}
    
    private PVPProtobuf.RoomInfo _room_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PVPProtobuf.RoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.RoomInfo.MemberInfo> _new_member_info = new global::System.Collections.Generic.List<PVPProtobuf.RoomInfo.MemberInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"new_member_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.RoomInfo.MemberInfo> new_member_info
    {
      get { return _new_member_info; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_NewRoomMaster_Response")]
  public partial class Room_NewRoomMaster_Response : global::ProtoBuf.IExtensible
  {
    public Room_NewRoomMaster_Response() {}
    
    private int _room_master_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_master_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_master_uid
    {
      get { return _room_master_uid; }
      set { _room_master_uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_StartGame_Request")]
  public partial class Room_StartGame_Request : global::ProtoBuf.IExtensible
  {
    public Room_StartGame_Request() {}
    
    private int _ext;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ext
    {
      get { return _ext; }
      set { _ext = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_FinishGame_Request")]
  public partial class Room_FinishGame_Request : global::ProtoBuf.IExtensible
  {
    public Room_FinishGame_Request() {}
    
    private int _ext;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ext
    {
      get { return _ext; }
      set { _ext = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_EnterRandomRoom_Request")]
  public partial class Room_EnterRandomRoom_Request : global::ProtoBuf.IExtensible
  {
    public Room_EnterRandomRoom_Request() {}
    
    private int _ext;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ext
    {
      get { return _ext; }
      set { _ext = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_EnterRandomRoom_Response")]
  public partial class Room_EnterRandomRoom_Response : global::ProtoBuf.IExtensible
  {
    public Room_EnterRandomRoom_Response() {}
    
    private PVPProtobuf.RoomInfo _room_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PVPProtobuf.RoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_LeaveRoom_Request")]
  public partial class Room_LeaveRoom_Request : global::ProtoBuf.IExtensible
  {
    public Room_LeaveRoom_Request() {}
    
    private int _ext;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ext", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ext
    {
      get { return _ext; }
      set { _ext = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_LeaveRoom_Response")]
  public partial class Room_LeaveRoom_Response : global::ProtoBuf.IExtensible
  {
    public Room_LeaveRoom_Response() {}
    
    private int _lobby_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"lobby_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lobby_id
    {
      get { return _lobby_id; }
      set { _lobby_id = value; }
    }
    private int _room_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_OtherMemberLeaveRoom_Response")]
  public partial class Room_OtherMemberLeaveRoom_Response : global::ProtoBuf.IExtensible
  {
    public Room_OtherMemberLeaveRoom_Response() {}
    
    private readonly global::System.Collections.Generic.List<uint> _member_ids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"member_ids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> member_ids
    {
      get { return _member_ids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Chat_SendChat_Request")]
  public partial class Chat_SendChat_Request : global::ProtoBuf.IExtensible
  {
    public Chat_SendChat_Request() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Chat_SendChat_Response")]
  public partial class Chat_SendChat_Response : global::ProtoBuf.IExtensible
  {
    public Chat_SendChat_Response() {}
    
    private int _chat_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chat_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chat_uid
    {
      get { return _chat_uid; }
      set { _chat_uid = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Message_CustomTargetMessage_Request")]
  public partial class Message_CustomTargetMessage_Request : global::ProtoBuf.IExtensible
  {
    public Message_CustomTargetMessage_Request() {}
    
    private uint _target_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"target_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint target_uid
    {
      get { return _target_uid; }
      set { _target_uid = value; }
    }
    private int _custom_command_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"custom_command_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int custom_command_id
    {
      get { return _custom_command_id; }
      set { _custom_command_id = value; }
    }
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Message_CustomTargetMessage_Response")]
  public partial class Message_CustomTargetMessage_Response : global::ProtoBuf.IExtensible
  {
    public Message_CustomTargetMessage_Response() {}
    
    private int _from_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"from_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int from_uid
    {
      get { return _from_uid; }
      set { _from_uid = value; }
    }
    private int _custom_command_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"custom_command_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int custom_command_id
    {
      get { return _custom_command_id; }
      set { _custom_command_id = value; }
    }
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_NewMessage_Request")]
  public partial class Room_NewMessage_Request : global::ProtoBuf.IExtensible
  {
    public Room_NewMessage_Request() {}
    
    private int _custom_command_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"custom_command_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int custom_command_id
    {
      get { return _custom_command_id; }
      set { _custom_command_id = value; }
    }
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private int _target_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"target_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target_type
    {
      get { return _target_type; }
      set { _target_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_NewMessage_Broadcast")]
  public partial class Room_NewMessage_Broadcast : global::ProtoBuf.IExtensible
  {
    public Room_NewMessage_Broadcast() {}
    
    private uint _from_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"from_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint from_uid
    {
      get { return _from_uid; }
      set { _from_uid = value; }
    }
    private int _custom_command_id;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"custom_command_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int custom_command_id
    {
      get { return _custom_command_id; }
      set { _custom_command_id = value; }
    }
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_SendChat_Request")]
  public partial class Room_SendChat_Request : global::ProtoBuf.IExtensible
  {
    public Room_SendChat_Request() {}
    
    private string _message;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_SendChat_Response")]
  public partial class Room_SendChat_Response : global::ProtoBuf.IExtensible
  {
    public Room_SendChat_Response() {}
    
    private int _chat_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"chat_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int chat_uid
    {
      get { return _chat_uid; }
      set { _chat_uid = value; }
    }
    private string _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_SendRoomCacheMessage_Request")]
  public partial class Room_SendRoomCacheMessage_Request : global::ProtoBuf.IExtensible
  {
    public Room_SendRoomCacheMessage_Request() {}
    
    private int _message_id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"message_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int message_id
    {
      get { return _message_id; }
      set { _message_id = value; }
    }
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_ReceiveRoomCacheMessage_Response")]
  public partial class Room_ReceiveRoomCacheMessage_Response : global::ProtoBuf.IExtensible
  {
    public Room_ReceiveRoomCacheMessage_Response() {}
    
    private int _from_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"from_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int from_uid
    {
      get { return _from_uid; }
      set { _from_uid = value; }
    }
    private int _cache_message_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cache_message_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int cache_message_number
    {
      get { return _cache_message_number; }
      set { _cache_message_number = value; }
    }
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_RoomCacheMessageList_Request")]
  public partial class Room_RoomCacheMessageList_Request : global::ProtoBuf.IExtensible
  {
    public Room_RoomCacheMessageList_Request() {}
    
    private uint _cache_message_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cache_message_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cache_message_number
    {
      get { return _cache_message_number; }
      set { _cache_message_number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomCacheMessage")]
  public partial class RoomCacheMessage : global::ProtoBuf.IExtensible
  {
    public RoomCacheMessage() {}
    
    private int _from_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"from_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int from_uid
    {
      get { return _from_uid; }
      set { _from_uid = value; }
    }
    private byte[] _message;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_RoomCacheMessageList_Response")]
  public partial class Room_RoomCacheMessageList_Response : global::ProtoBuf.IExtensible
  {
    public Room_RoomCacheMessageList_Response() {}
    
    private uint _cache_message_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"cache_message_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint cache_message_number
    {
      get { return _cache_message_number; }
      set { _cache_message_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.RoomCacheMessage> _room_cache_message_list = new global::System.Collections.Generic.List<PVPProtobuf.RoomCacheMessage>();
    [global::ProtoBuf.ProtoMember(2, Name=@"room_cache_message_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.RoomCacheMessage> room_cache_message_list
    {
      get { return _room_cache_message_list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_StartBattle_Request")]
  public partial class Room_StartBattle_Request : global::ProtoBuf.IExtensible
  {
    public Room_StartBattle_Request() {}
    
    private uint _increment_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"increment_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint increment_number
    {
      get { return _increment_number; }
      set { _increment_number = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _turn_order = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"turn_order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> turn_order
    {
      get { return _turn_order; }
    }
  
    private byte[] _message = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_StartBattle_Response")]
  public partial class Room_StartBattle_Response : global::ProtoBuf.IExtensible
  {
    public Room_StartBattle_Response() {}
    
    private uint _increment_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"increment_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint increment_number
    {
      get { return _increment_number; }
      set { _increment_number = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _turn_order = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(2, Name=@"turn_order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> turn_order
    {
      get { return _turn_order; }
    }
  
    private byte[] _message = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"message", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] message
    {
      get { return _message; }
      set { _message = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_NextTurn_Request")]
  public partial class Room_NextTurn_Request : global::ProtoBuf.IExtensible
  {
    public Room_NextTurn_Request() {}
    
    private readonly global::System.Collections.Generic.List<uint> _turn_order = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"turn_order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> turn_order
    {
      get { return _turn_order; }
    }
  
    private byte[] _room_data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] room_data
    {
      get { return _room_data; }
      set { _room_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_NextTurn_Response")]
  public partial class Room_NextTurn_Response : global::ProtoBuf.IExtensible
  {
    public Room_NextTurn_Response() {}
    
    private uint _room_data_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_data_number
    {
      get { return _room_data_number; }
      set { _room_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _turn_order = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"turn_order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> turn_order
    {
      get { return _turn_order; }
    }
  
    private byte[] _room_data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"room_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] room_data
    {
      get { return _room_data; }
      set { _room_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_NextTurn_Broadcast")]
  public partial class Room_NextTurn_Broadcast : global::ProtoBuf.IExtensible
  {
    public Room_NextTurn_Broadcast() {}
    
    private uint _room_data_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_data_number
    {
      get { return _room_data_number; }
      set { _room_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _turn_order = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(2, Name=@"turn_order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> turn_order
    {
      get { return _turn_order; }
    }
  
    private byte[] _room_data;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"room_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] room_data
    {
      get { return _room_data; }
      set { _room_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_UpdateMemberCustomData_Request")]
  public partial class Room_UpdateMemberCustomData_Request : global::ProtoBuf.IExtensible
  {
    public Room_UpdateMemberCustomData_Request() {}
    
    private int _update_range;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"update_range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int update_range
    {
      get { return _update_range; }
      set { _update_range = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _being_updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(2, Name=@"being_updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> being_updated_data
    {
      get { return _being_updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _being_deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"being_deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> being_deleted_data
    {
      get { return _being_deleted_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _check_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(4, Name=@"check_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> check_data
    {
      get { return _check_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _check_data_not_exist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"check_data_not_exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> check_data_not_exist
    {
      get { return _check_data_not_exist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_UpdateMemberCustomData_Response")]
  public partial class Room_UpdateMemberCustomData_Response : global::ProtoBuf.IExtensible
  {
    public Room_UpdateMemberCustomData_Response() {}
    
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(2, Name=@"updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> updated_data
    {
      get { return _updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> deleted_data
    {
      get { return _deleted_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _check_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(4, Name=@"check_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> check_data
    {
      get { return _check_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _check_data_not_exist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"check_data_not_exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> check_data_not_exist
    {
      get { return _check_data_not_exist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_UpdateMemberCustomData_Broadcast")]
  public partial class Room_UpdateMemberCustomData_Broadcast : global::ProtoBuf.IExtensible
  {
    public Room_UpdateMemberCustomData_Broadcast() {}
    
    private uint _member_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"member_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint member_uid
    {
      get { return _member_uid; }
      set { _member_uid = value; }
    }
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(3, Name=@"updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> updated_data
    {
      get { return _updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> deleted_data
    {
      get { return _deleted_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_UpdateRoomCustomData_Request")]
  public partial class Room_UpdateRoomCustomData_Request : global::ProtoBuf.IExtensible
  {
    public Room_UpdateRoomCustomData_Request() {}
    
    private int _update_range;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"update_range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int update_range
    {
      get { return _update_range; }
      set { _update_range = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _being_updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(2, Name=@"being_updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> being_updated_data
    {
      get { return _being_updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _being_deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"being_deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> being_deleted_data
    {
      get { return _being_deleted_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _check_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(4, Name=@"check_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> check_data
    {
      get { return _check_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _check_data_not_exist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"check_data_not_exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> check_data_not_exist
    {
      get { return _check_data_not_exist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_UpdateRoomCustomData_Response")]
  public partial class Room_UpdateRoomCustomData_Response : global::ProtoBuf.IExtensible
  {
    public Room_UpdateRoomCustomData_Response() {}
    
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(2, Name=@"updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> updated_data
    {
      get { return _updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> deleted_data
    {
      get { return _deleted_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _check_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(4, Name=@"check_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> check_data
    {
      get { return _check_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _check_data_not_exist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"check_data_not_exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> check_data_not_exist
    {
      get { return _check_data_not_exist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_UpdateRoomCustomData_Broadcast")]
  public partial class Room_UpdateRoomCustomData_Broadcast : global::ProtoBuf.IExtensible
  {
    public Room_UpdateRoomCustomData_Broadcast() {}
    
    private uint _member_uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"member_uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint member_uid
    {
      get { return _member_uid; }
      set { _member_uid = value; }
    }
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(3, Name=@"updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> updated_data
    {
      get { return _updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> deleted_data
    {
      get { return _deleted_data; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_RandomList_Request")]
  public partial class Room_RandomList_Request : global::ProtoBuf.IExtensible
  {
    public Room_RandomList_Request() {}
    
    private int _number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int number
    {
      get { return _number; }
      set { _number = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_RandomList_Broadcast")]
  public partial class Room_RandomList_Broadcast : global::ProtoBuf.IExtensible
  {
    public Room_RandomList_Broadcast() {}
    
    private readonly global::System.Collections.Generic.List<int> _items = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(1, Name=@"items", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> items
    {
      get { return _items; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_MatchOpponent_Request")]
  public partial class Room_MatchOpponent_Request : global::ProtoBuf.IExtensible
  {
    public Room_MatchOpponent_Request() {}
    
    private int _standard;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"standard", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int standard
    {
      get { return _standard; }
      set { _standard = value; }
    }
    private int _range = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"range", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int range
    {
      get { return _range; }
      set { _range = value; }
    }
    private int _wait_for_match = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"wait_for_match", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wait_for_match
    {
      get { return _wait_for_match; }
      set { _wait_for_match = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_MatchOpponent_Response")]
  public partial class Room_MatchOpponent_Response : global::ProtoBuf.IExtensible
  {
    public Room_MatchOpponent_Response() {}
    
    private PVPProtobuf.RoomInfo _room_info;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_info", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PVPProtobuf.RoomInfo room_info
    {
      get { return _room_info; }
      set { _room_info = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo> _appuser_infos = new global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"appuser_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo> appuser_infos
    {
      get { return _appuser_infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_OtherLoseConnection_Broadcast")]
  public partial class Room_OtherLoseConnection_Broadcast : global::ProtoBuf.IExtensible
  {
    public Room_OtherLoseConnection_Broadcast() {}
    
    private uint _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_CheckData_Request")]
  public partial class Room_CheckData_Request : global::ProtoBuf.IExtensible
  {
    public Room_CheckData_Request() {}
    
    private uint _i;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"i", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint i
    {
      get { return _i; }
      set { _i = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_CompleteBattle_Request")]
  public partial class Room_CompleteBattle_Request : global::ProtoBuf.IExtensible
  {
    public Room_CompleteBattle_Request() {}
    
    private byte[] _room_data;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] room_data
    {
      get { return _room_data; }
      set { _room_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_CompleteBattle_Broadcast")]
  public partial class Room_CompleteBattle_Broadcast : global::ProtoBuf.IExtensible
  {
    public Room_CompleteBattle_Broadcast() {}
    
    private uint _room_data_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"room_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint room_data_number
    {
      get { return _room_data_number; }
      set { _room_data_number = value; }
    }
    private byte[] _room_data;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"room_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public byte[] room_data
    {
      get { return _room_data; }
      set { _room_data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Friend")]
  public partial class Friend : global::ProtoBuf.IExtensible
  {
    public Friend() {}
    
    private uint _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private uint _is_online;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"is_online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint is_online
    {
      get { return _is_online; }
      set { _is_online = value; }
    }
    private uint _room_id = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"room_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint room_id
    {
      get { return _room_id; }
      set { _room_id = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Room_GetFriendsState_Response")]
  public partial class Room_GetFriendsState_Response : global::ProtoBuf.IExtensible
  {
    public Room_GetFriendsState_Response() {}
    
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Friend> _friends = new global::System.Collections.Generic.List<PVPProtobuf.Friend>();
    [global::ProtoBuf.ProtoMember(1, Name=@"friends", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Friend> friends
    {
      get { return _friends; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppUser_UpdateInfo_Request")]
  public partial class AppUser_UpdateInfo_Request : global::ProtoBuf.IExtensible
  {
    public AppUser_UpdateInfo_Request() {}
    
    private int _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _win_times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int win_times
    {
      get { return _win_times; }
      set { _win_times = value; }
    }
    private int _lose_times;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lose_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lose_times
    {
      get { return _lose_times; }
      set { _lose_times = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _being_updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(5, Name=@"being_updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> being_updated_data
    {
      get { return _being_updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _being_deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(6, Name=@"being_deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> being_deleted_data
    {
      get { return _being_deleted_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _check_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(7, Name=@"check_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> check_data
    {
      get { return _check_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _check_data_not_exist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(8, Name=@"check_data_not_exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> check_data_not_exist
    {
      get { return _check_data_not_exist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Appuser_UpdateInfo_Response")]
  public partial class Appuser_UpdateInfo_Response : global::ProtoBuf.IExtensible
  {
    public Appuser_UpdateInfo_Response() {}
    
    private int _level;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"level", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int level
    {
      get { return _level; }
      set { _level = value; }
    }
    private long _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public long score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _win_times;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"win_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int win_times
    {
      get { return _win_times; }
      set { _win_times = value; }
    }
    private int _lose_times;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"lose_times", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int lose_times
    {
      get { return _lose_times; }
      set { _lose_times = value; }
    }
    private uint _number;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint number
    {
      get { return _number; }
      set { _number = value; }
    }
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(7, Name=@"updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> updated_data
    {
      get { return _updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(8, Name=@"deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> deleted_data
    {
      get { return _deleted_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _check_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(9, Name=@"check_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> check_data
    {
      get { return _check_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _check_data_not_exist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(10, Name=@"check_data_not_exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> check_data_not_exist
    {
      get { return _check_data_not_exist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppUser_UpdateCustomData_Request")]
  public partial class AppUser_UpdateCustomData_Request : global::ProtoBuf.IExtensible
  {
    public AppUser_UpdateCustomData_Request() {}
    
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _being_updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(1, Name=@"being_updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> being_updated_data
    {
      get { return _being_updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _being_deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"being_deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> being_deleted_data
    {
      get { return _being_deleted_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _check_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(3, Name=@"check_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> check_data
    {
      get { return _check_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _check_data_not_exist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"check_data_not_exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> check_data_not_exist
    {
      get { return _check_data_not_exist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppUser_UpdateCustomData_Response")]
  public partial class AppUser_UpdateCustomData_Response : global::ProtoBuf.IExtensible
  {
    public AppUser_UpdateCustomData_Response() {}
    
    private uint _custom_data_number;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"custom_data_number", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint custom_data_number
    {
      get { return _custom_data_number; }
      set { _custom_data_number = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _updated_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(2, Name=@"updated_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> updated_data
    {
      get { return _updated_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _deleted_data = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(3, Name=@"deleted_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> deleted_data
    {
      get { return _deleted_data; }
    }
  
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Pair> _check_data = new global::System.Collections.Generic.List<PVPProtobuf.Pair>();
    [global::ProtoBuf.ProtoMember(4, Name=@"check_data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Pair> check_data
    {
      get { return _check_data; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _check_data_not_exist = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(5, Name=@"check_data_not_exist", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> check_data_not_exist
    {
      get { return _check_data_not_exist; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppUser_GetUserInfo_Request")]
  public partial class AppUser_GetUserInfo_Request : global::ProtoBuf.IExtensible
  {
    public AppUser_GetUserInfo_Request() {}
    
    private readonly global::System.Collections.Generic.List<uint> _member_uids = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(1, Name=@"member_uids", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> member_uids
    {
      get { return _member_uids; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AppUser_GetUserInfo_Response")]
  public partial class AppUser_GetUserInfo_Response : global::ProtoBuf.IExtensible
  {
    public AppUser_GetUserInfo_Response() {}
    
    private readonly global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo> _user_infos = new global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo>();
    [global::ProtoBuf.ProtoMember(1, Name=@"user_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.AppUserInfo> user_infos
    {
      get { return _user_infos; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard")]
  public partial class Leaderboard : global::ProtoBuf.IExtensible
  {
    public Leaderboard() {}
    
    private PVPProtobuf.Leaderboard.Mate _meta;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"meta", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PVPProtobuf.Leaderboard.Mate meta
    {
      get { return _meta; }
      set { _meta = value; }
    }
    private readonly global::System.Collections.Generic.List<PVPProtobuf.Leaderboard.UserInfo> _user_infos = new global::System.Collections.Generic.List<PVPProtobuf.Leaderboard.UserInfo>();
    [global::ProtoBuf.ProtoMember(2, Name=@"user_infos", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<PVPProtobuf.Leaderboard.UserInfo> user_infos
    {
      get { return _user_infos; }
    }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfo")]
  public partial class UserInfo : global::ProtoBuf.IExtensible
  {
    public UserInfo() {}
    
    private uint _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _avatar;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"avatar", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string avatar
    {
      get { return _avatar; }
      set { _avatar = value; }
    }
    private ulong _score;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong score
    {
      get { return _score; }
      set { _score = value; }
    }
    private readonly global::System.Collections.Generic.List<uint> _order = new global::System.Collections.Generic.List<uint>();
    [global::ProtoBuf.ProtoMember(5, Name=@"order", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<uint> order
    {
      get { return _order; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Mate")]
  public partial class Mate : global::ProtoBuf.IExtensible
  {
    public Mate() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private int _spatial_dimension;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"spatial_dimension", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int spatial_dimension
    {
      get { return _spatial_dimension; }
      set { _spatial_dimension = value; }
    }
    private int _time_dimension;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"time_dimension", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int time_dimension
    {
      get { return _time_dimension; }
      set { _time_dimension = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard_GetList_Request")]
  public partial class Leaderboard_GetList_Request : global::ProtoBuf.IExtensible
  {
    public Leaderboard_GetList_Request() {}
    
    private PVPProtobuf.Leaderboard.Mate _mate;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PVPProtobuf.Leaderboard.Mate mate
    {
      get { return _mate; }
      set { _mate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard_GetList_Response")]
  public partial class Leaderboard_GetList_Response : global::ProtoBuf.IExtensible
  {
    public Leaderboard_GetList_Response() {}
    
    private PVPProtobuf.Leaderboard _leaderboard;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"leaderboard", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public PVPProtobuf.Leaderboard leaderboard
    {
      get { return _leaderboard; }
      set { _leaderboard = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Leaderboard_SubmitScore_Request")]
  public partial class Leaderboard_SubmitScore_Request : global::ProtoBuf.IExtensible
  {
    public Leaderboard_SubmitScore_Request() {}
    
    private string _id;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private ulong _score;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ulong score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private int _submit_mark;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"submit_mark", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int submit_mark
    {
      get { return _submit_mark; }
      set { _submit_mark = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}