//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protobuf_token.proto
namespace PVPProtobuf_Token
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User_LoginOrRegister_Req")]
  public partial class User_LoginOrRegister_Req : global::ProtoBuf.IExtensible
  {
    public User_LoginOrRegister_Req() {}
    
    private string _app_key;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"app_key", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string app_key
    {
      get { return _app_key; }
      set { _app_key = value; }
    }
    private int _proto_version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"proto_version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int proto_version
    {
      get { return _proto_version; }
      set { _proto_version = value; }
    }
    private int _device_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"device_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int device_type
    {
      get { return _device_type; }
      set { _device_type = value; }
    }
    private int _login_type;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"login_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int login_type
    {
      get { return _login_type; }
      set { _login_type = value; }
    }
    private string _account = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _unique_identifier = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"unique_identifier", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string unique_identifier
    {
      get { return _unique_identifier; }
      set { _unique_identifier = value; }
    }
    private string _facebook_access_token = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"facebook_access_token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string facebook_access_token
    {
      get { return _facebook_access_token; }
      set { _facebook_access_token = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"User_LoginOrRegister_Res")]
  public partial class User_LoginOrRegister_Res : global::ProtoBuf.IExtensible
  {
    public User_LoginOrRegister_Res() {}
    
    private uint _uid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public uint uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private int _login_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"login_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int login_type
    {
      get { return _login_type; }
      set { _login_type = value; }
    }
    private string _ip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private int _port;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"port", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int port
    {
      get { return _port; }
      set { _port = value; }
    }
    private string _name;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}